blank_issues_enabled: false
contact_links:
  - name: ğŸ› Bug report
    url: https://github.com/HXSecurityBusiness/DongTai/issues/new?assignees=&labels=bug&template=bug_report.md
    about: Report a bug to help us improve DongTai

  - name: ğŸš€ Feature request
    url: https://github.com/HXSecurityBusiness/DongTai/issues/new?assignees=&labels=feature&template=feature_request.md
    about: Suggest an idea for DongTai

  - name: â“ Ask a question
    url: https://github.com/HXSecurityBusiness/DongTai/discussions/new?category=q-a
    about: Ask and discuss questions with other DongTai community members
